name: edu_iraq
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 
  intl: ^0.19.0 
  shared_preferences: ^2.0.15
  firebase_core:
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.1.0
  firebase_messaging: ^15.0.3
  flutter_spinkit: ^5.1.0
  uuid:
  short_uuids: ^2.0.0
#  audioplayers: ^6.0.0
  curved_navigation_bar: ^1.0.1
  material_design_icons_flutter: ^7.0.7296
  share_plus: ^9.0.0
  file_picker: ^8.0.6
  firebase_storage: ^12.1.1
  provider: ^6.0.0
  animated_snack_bar: ^0.4.0
  flutter_local_notifications: ^17.2.1+2
  awesome_notifications: ^0.9.3+1
  firebase_messaging_platform_interface: ^4.5.41
  flutter_animate:
  carousel_slider:
  animated_button:
  flutter_staggered_grid_view: ^0.7.0
  icons_plus: ^5.0.0
  screen_protector: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 
  flutter_gen: any 

flutter_native_splash:
  image: assets/images/ima_onboarding.webp
  color: "#00CCFF"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/voices/

  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Bold.ttf
        - asset: assets/fonts/Amiri-BoldItalic.ttf
        - asset: assets/fonts/Amiri-Italic.ttf
        - asset: assets/fonts/Amiri-Regular.ttf
          weight: 700