// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg7WEd3NvB6gGoU_Y3BwH3-32vMIrvxu8',
    appId: '1:206016873227:web:fa8bbac23101ae9743d80e',
    messagingSenderId: '206016873227',
    projectId: 'educationapp-3a344',
    authDomain: 'educationapp-3a344.firebaseapp.com',
    storageBucket: 'educationapp-3a344.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKqJXG6gzQoRni1Pnr88uX2SWSBbhqCCM',
    appId: '1:206016873227:android:0f5624e9de382f0c43d80e',
    messagingSenderId: '206016873227',
    projectId: 'educationapp-3a344',
    storageBucket: 'educationapp-3a344.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbOE4kDGV9ZwNhbgbc2Spffa_pF432Orw',
    appId: '1:206016873227:ios:52828a503caf27af43d80e',
    messagingSenderId: '206016873227',
    projectId: 'educationapp-3a344',
    storageBucket: 'educationapp-3a344.appspot.com',
    iosBundleId: 'com.eduoferaq.edu.net.eduiraq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbOE4kDGV9ZwNhbgbc2Spffa_pF432Orw',
    appId: '1:206016873227:ios:52828a503caf27af43d80e',
    messagingSenderId: '206016873227',
    projectId: 'educationapp-3a344',
    storageBucket: 'educationapp-3a344.appspot.com',
    iosBundleId: 'com.eduoferaq.edu.net.eduiraq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDg7WEd3NvB6gGoU_Y3BwH3-32vMIrvxu8',
    appId: '1:206016873227:web:ab0e353878aa5f3843d80e',
    messagingSenderId: '206016873227',
    projectId: 'educationapp-3a344',
    authDomain: 'educationapp-3a344.firebaseapp.com',
    storageBucket: 'educationapp-3a344.appspot.com',
  );
}
